// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMpC24ioWNodq-jyzloyCjJw7yEo6x-J4',
    appId: '1:663187950374:web:0638f87c5d59d6f0c94fe7',
    messagingSenderId: '663187950374',
    projectId: 'learningauth-48935',
    authDomain: 'learningauth-48935.firebaseapp.com',
    storageBucket: 'learningauth-48935.appspot.com',
    measurementId: 'G-5TQEFM8YDP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3KmTuqRRgY4szyveEKKCRh2HjD7qsx5k',
    appId: '1:663187950374:android:2e456eda86067f40c94fe7',
    messagingSenderId: '663187950374',
    projectId: 'learningauth-48935',
    storageBucket: 'learningauth-48935.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0wE3J1sDHNlvlQCZP7U5aj8WUDSmf3DM',
    appId: '1:663187950374:ios:812a37b9b09b91d8c94fe7',
    messagingSenderId: '663187950374',
    projectId: 'learningauth-48935',
    storageBucket: 'learningauth-48935.appspot.com',
    iosClientId: '663187950374-nho3ue925dja5le949rq7ftu2et84e8r.apps.googleusercontent.com',
    iosBundleId: 'com.example.signupSignin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD0wE3J1sDHNlvlQCZP7U5aj8WUDSmf3DM',
    appId: '1:663187950374:ios:812a37b9b09b91d8c94fe7',
    messagingSenderId: '663187950374',
    projectId: 'learningauth-48935',
    storageBucket: 'learningauth-48935.appspot.com',
    iosClientId: '663187950374-nho3ue925dja5le949rq7ftu2et84e8r.apps.googleusercontent.com',
    iosBundleId: 'com.example.signupSignin',
  );
}
